# NOTE:
# This workflow assumes Azure Container Registry (ACR).
# Current deployment uses Docker Hub + manual restarts.
# Enable when migrating to ACR.

name: Deploy to Azure Web Service

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/deploy-production.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: vozpublica-api
  REGISTRY_NAME: vozpublicaacr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_NAME }}.azurecr.io/vozpublica-api
        tags: |
          type=sha,prefix={{branch}}-
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY_NAME }}.azurecr.io/vozpublica-api:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY_NAME }}.azurecr.io/vozpublica-api:buildcache,mode=max
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.REGISTRY_NAME }}.azurecr.io/vozpublica-api:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    
    - name: Health Check
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        
        HEALTH_URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health"
        echo "Checking health at: $HEALTH_URL"
        
        for i in {1..10}; do
          if curl -f -s "$HEALTH_URL" > /dev/null; then
            echo "✅ Health check passed!"
            exit 0
          fi
          echo "Attempt $i failed, retrying in 10s..."
          sleep 10
        done
        
        echo "❌ Health check failed after 10 attempts"
        exit 1
